CREATE DATABASE SpotifyDB;
GO

USE SpotifyDB;
GO

CREATE TABLE SearchHistory (
	Id INT PRIMARY KEY IDENTITY(1,1),
	SearchQuery NVARCHAR(255) NOT NULL,
	SearchDate DATETIME NOT NULL,
	ResultCount INT NOT NULL
);
CREATE TABLE UserPreferences (
Id INT PRIMARY KEY IDENTITY(1,1),
TrackId NVARCHAR(255) NOT NULL,
TrackName NVARCHAR(255)NOT NULL,
ArtistName NVARCHAR(255)NOT NULL,
PlayedDate DATETIME NOT NULL,
PlayCount INT NOT NULL DEFAULT 1

);

